//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmrWorkflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmrWorkflow.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3://elasticmapreduce/libs/state-pusher/0.1/fetch.
        /// </summary>
        internal static string DebugStepArg {
            get {
                return ResourceManager.GetString("DebugStepArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3://elasticmapreduce/libs/script-runner/script-runner.jar.
        /// </summary>
        internal static string DebugStepJarPath {
            get {
                return ResourceManager.GetString("DebugStepJarPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start debugging.
        /// </summary>
        internal static string DebugStepName {
            get {
                return ResourceManager.GetString("DebugStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is missing for the BootstrapAction. Example: &quot;upload libs&quot;.
        /// </summary>
        internal static string E_BootstrapactionNameIsMissing {
            get {
                return ResourceManager.GetString("E_BootstrapactionNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path property is missing for the BootstrapAction. Example: &quot;s3://mapreduceBucket/bootstrap/action.sh&quot;.
        /// </summary>
        internal static string E_BootstrapactionPathIsMissing {
            get {
                return ResourceManager.GetString("E_BootstrapactionPathIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key property is missing for the Cluster Tag. Example: &quot;Contact&quot;.
        /// </summary>
        internal static string E_ClusterTagKeyIsMissing {
            get {
                return ResourceManager.GetString("E_ClusterTagKeyIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value property is missing for the Cluster Tag. Example: &quot;SupperSlonic.com&quot;.
        /// </summary>
        internal static string E_ClusterTagValueIsMissing {
            get {
                return ResourceManager.GetString("E_ClusterTagValueIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackupPath property is missing for the HBase Backup Step. Example: &quot;s3://myBucket/hBaseBackup&quot;.
        /// </summary>
        internal static string E_HBaseBackupPathIsMissing {
            get {
                return ResourceManager.GetString("E_HBaseBackupPathIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JarPath property is missing for the HBase Configuration. Example: &quot;/home/hadoop/lib/hbase-0.94.7.jar&quot;.
        /// </summary>
        internal static string E_HBaseJarPathIsMissing {
            get {
                return ResourceManager.GetString("E_HBaseJarPathIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestorePath property is missing for the HBase Restore Step. Example: &quot;s3://myBucket/hBaseRestore&quot;.
        /// </summary>
        internal static string E_HBaseRestorePathIsMissing {
            get {
                return ResourceManager.GetString("E_HBaseRestorePathIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmiVersion property is missing for the JobFlow. Examples: &quot;latest&quot;, &quot;3.0.3&quot;.
        /// </summary>
        internal static string E_JobFlowAmiVersionIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowAmiVersionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ec2KeyName property is missing for the JobFlow. Example: &quot;testEC2Key&quot;.
        /// </summary>
        internal static string E_JobFlowEc2KeyNameIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowEc2KeyNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HadoopVersion property is missing for the JobFlow. Example: &quot;2.2.0&quot;.
        /// </summary>
        internal static string E_JobFlowHadoopVersionIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowHadoopVersionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceCount property of the JobFlow should be positive. Example: &quot;34&quot;.
        /// </summary>
        internal static string E_JobFlowInstanceCountShouldBePositive {
            get {
                return ResourceManager.GetString("E_JobFlowInstanceCountShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogUri property is missing for the JobFlow. Example: &quot;s3://myBucket/logs&quot;.
        /// </summary>
        internal static string E_JobFlowLogUriIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowLogUriIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterInstanceType property is missing for the JobFlow. Example: &quot;m1.medium&quot;.
        /// </summary>
        internal static string E_JobFlowMasterInstanceTypeIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowMasterInstanceTypeIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is missing for the JobFlow. Example: &quot;my super job 1&quot;.
        /// </summary>
        internal static string E_JobFlowNameIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlaveInstanceType property is missing for the JobFlow. Example: &quot;m3.2xlarge&quot;.
        /// </summary>
        internal static string E_JobFlowSlaveInstanceTypeIsMissing {
            get {
                return ResourceManager.GetString("E_JobFlowSlaveInstanceTypeIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JarPath property is missing for the Step. Example: &quot;s3://mapreduceBucket/jar/myPackage.jar&quot;.
        /// </summary>
        internal static string E_StepJarPathIsMissing {
            get {
                return ResourceManager.GetString("E_StepJarPathIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name property is missing for the Step. Example: &quot;map-reduce job 1&quot;.
        /// </summary>
        internal static string E_StepNameIsMissing {
            get {
                return ResourceManager.GetString("E_StepNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported element &quot;{0}&quot;.
        /// </summary>
        internal static string E_UnsupportedXmlElement {
            get {
                return ResourceManager.GetString("E_UnsupportedXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Hadoop.
        /// </summary>
        internal static string HadoopConfigName {
            get {
                return ResourceManager.GetString("HadoopConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3://elasticmapreduce/bootstrap-actions/configure-hadoop.
        /// </summary>
        internal static string HadoopConfigPath {
            get {
                return ResourceManager.GetString("HadoopConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup HBase.
        /// </summary>
        internal static string HBaseBackupStepName {
            get {
                return ResourceManager.GetString("HBaseBackupStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure HBase.
        /// </summary>
        internal static string HBaseConfigName {
            get {
                return ResourceManager.GetString("HBaseConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3://elasticmapreduce/bootstrap-actions/configure-hbase.
        /// </summary>
        internal static string HBaseConfigPath {
            get {
                return ResourceManager.GetString("HBaseConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure HBase Daemons.
        /// </summary>
        internal static string HBaseDaemonsConfigName {
            get {
                return ResourceManager.GetString("HBaseDaemonsConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3://elasticmapreduce/bootstrap-actions/configure-hbase-daemons.
        /// </summary>
        internal static string HBaseDaemonsConfigPath {
            get {
                return ResourceManager.GetString("HBaseDaemonsConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install HBase.
        /// </summary>
        internal static string HBaseInstallName {
            get {
                return ResourceManager.GetString("HBaseInstallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s3://elasticmapreduce/bootstrap-actions/setup-hbase.
        /// </summary>
        internal static string HBaseInstallPath {
            get {
                return ResourceManager.GetString("HBaseInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emr.hbase.backup.Main.
        /// </summary>
        internal static string HBaseMainClass {
            get {
                return ResourceManager.GetString("HBaseMainClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore HBase.
        /// </summary>
        internal static string HBaseRestoreStepName {
            get {
                return ResourceManager.GetString("HBaseRestoreStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start HBase.
        /// </summary>
        internal static string HBaseStepName {
            get {
                return ResourceManager.GetString("HBaseStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding activity: {0}.
        /// </summary>
        internal static string Info_AddingActivityTemplate {
            get {
                return ResourceManager.GetString("Info_AddingActivityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------.
        /// </summary>
        internal static string Info_CheckingJobStatus {
            get {
                return ResourceManager.GetString("Info_CheckingJobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully....
        /// </summary>
        internal static string Info_CompletedSuccessfully {
            get {
                return ResourceManager.GetString("Info_CompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed with errors....
        /// </summary>
        internal static string Info_CompletedWithErrors {
            get {
                return ResourceManager.GetString("Info_CompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMR Service returned not OK response code.
        /// </summary>
        internal static string Info_EmrServiceNotOkResponse {
            get {
                return ResourceManager.GetString("Info_EmrServiceNotOkResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during sending the request: {0}.
        /// </summary>
        internal static string Info_ExceptionWhenSendingRequestTemplate {
            get {
                return ResourceManager.GetString("Info_ExceptionWhenSendingRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest step failed...
        ///The job&apos;s latest state: {0}.
        /// </summary>
        internal static string Info_FailToRunJobTemplate {
            get {
                return ResourceManager.GetString("Info_FailToRunJobTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Step:	{0}
        ///Latest State:	{1}
        ///Master URL:	{2}.
        /// </summary>
        internal static string Info_JobCurrentStateTemplate {
            get {
                return ResourceManager.GetString("Info_JobCurrentStateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job id:		.
        /// </summary>
        internal static string Info_JobFlowId {
            get {
                return ResourceManager.GetString("Info_JobFlowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not yet defined.
        /// </summary>
        internal static string Info_MasterPublicDnsNameNotDefined {
            get {
                return ResourceManager.GetString("Info_MasterPublicDnsNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no running step.
        /// </summary>
        internal static string Info_RunningStepNotDefined {
            get {
                return ResourceManager.GetString("Info_RunningStepNotDefined", resourceCulture);
            }
        }
    }
}
